version: '3.1'
services:

  ewm-service:
    build: ./service
    container_name: service
    environment:
      - EXPLORE-WITH-ME-STATISTICS_URL=http://stats:9090
    depends_on:
      - gateway
    ports:
      - "9091:9091"


  stats-server:
    build: ./statistics
    container_name: stats
    depends_on:
      - gateway
    ports:
      - "9090:9090"


