version: '3.1'
services:
 ## gateway
  ewm-service:
    build: ./api-gateway
    image: amazoncorretto:11-alpine-jdk
    container_name: gateway
    environment:
      - EXPLORE-WITH-ME-SERVICE_URL=http://service:9091/explore-with-me-service

    ports:
      - "8080:8080"

    ## ewm-service
  gateway:
    build: ./service
    image: amazoncorretto:11-alpine-jdk
    container_name: service
    environment:
      - EXPLORE-WITH-ME-STATISTICS_URL=http://stats:9090
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:resource
    depends_on:
      - ewm-service
    ports:
      - "9091:9091"


  stats-server:
    build: ./statistics
    image: amazoncorretto:11-alpine-jdk
    container_name: stats
    environment:
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:resource
    depends_on:
      - ewm-service
    ports:
      - "9090:9090"