version: '3.1'
services:

  ewm-service:
    build: ./service
    image: amazoncorretto:11-alpine-jdk
    container_name: service
    environment:
      - EXPLORE-WITH-ME-STATISTICS_URL=http://stats:9090
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:resource
    depends_on:
      - gateway
    ports:
      - "9091:9091"


  stats-server:
    build: ./statistics
    image: amazoncorretto:11-alpine-jdk
    container_name: stats
    environment:
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:resource
    depends_on:
      - gateway
    ports:
      - "9090:9090"