DROP TABLE IF EXISTS ENDPOINT_STATS_TABLE;

CREATE TABLE IF NOT EXISTS ENDPOINT_STATS_TABLE
(
    ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_ID   BIGINT,
    APP        VARCHAR(128),
    URI        TEXT,
    IP         VARCHAR(32),
    TIME_STAMP DATETIME
);